/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_JNI */

#ifndef _Included_JNI_JNI
#define _Included_JNI_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_JNI
 * Method:    JniAdd
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JNI_JNI_JniAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNI_JNI
 * Method:    JniSub
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JNI_JNI_JniSub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNI_JNI
 * Method:    JniMult
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JNI_JNI_JniMult
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNI_JNI
 * Method:    JniDiv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JNI_JNI_JniDiv
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     JNI_JNI
 * Method:    JniPow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JNI_JNI_JniPow
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNI_JNI
 * Method:    JniSqrt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNI_JNI_JniSqrt
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNI_JNI
 * Method:    JniMod
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JNI_JNI_JniMod
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
